volumes:

  pg_data:
  static_value:
  media_value:


services:

  backend-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - .env
    command:
      - sh
      - -c
      - |
        sleep 2 && cd cash &&
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/