# Generated by Django 3.2.16 on 2024-02-29 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождение'), ('wedding', 'Свадьба'), ('new_year', 'Новый год')], help_text='Введите повод для сбора', max_length=50, verbose_name='Повод для сбора')),
                ('name', models.CharField(help_text='Введите название сбора', max_length=50, verbose_name='Название сбора')),
                ('description', models.TextField(help_text='Введите описание сбора', verbose_name='Описание сбора')),
                ('purpose', models.PositiveIntegerField(help_text='Введите сумму, которую планируете собрать', verbose_name='Сумма, которую запланировали собрать')),
                ('current_money', models.PositiveIntegerField(verbose_name='Сумма, которую собрали на текущий момент')),
                ('count_people', models.PositiveIntegerField(verbose_name='Количество людей, уже сделавших пожертвования')),
                ('logo', models.ImageField(help_text='Загрузите картинку', null=True, upload_to='collects/images/logo', verbose_name='Обложка сбора')),
                ('date_time_collect', models.DateTimeField(help_text='Введите дату и время завершения сбора', verbose_name='Дата и время завершения сбора')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(help_text='Введите сумму пожертвования', verbose_name='Сумма пожертвования')),
                ('date_time_payment', models.DateTimeField(verbose_name='Дата и время платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collects.collect')),
                ('donating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
