# Generated by Django 3.2.16 on 2024-03-01 11:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='count_people',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='current_money',
        ),
        migrations.AlterField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='purpose',
            field=models.PositiveIntegerField(help_text='Введите сумму, которую планируете собрать', validators=[django.core.validators.MinValueValidator(1, 'Нужно постараться собрать хоть, что-то')], verbose_name='Сумма, которую запланировали собрать'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='collects.collect', verbose_name='Групповой денежный сбор'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_time_payment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='donating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, делающий пожертвование'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='money',
            field=models.PositiveIntegerField(help_text='Введите сумму пожертвования', validators=[django.core.validators.MinValueValidator(1, 'Пожертвуйте хоть что-нибудь')], verbose_name='Сумма пожертвования'),
        ),
    ]
