# Generated by Django 3.2.16 on 2024-03-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_auto_20240301_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name': 'Групповой денежный сбор', 'verbose_name_plural': 'Групповые денежные сборы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
